name: Test Manual workflow

on:
    workflow_dispatch:
        inputs:
            Environment:
                description: 'Environment to deploy'
                required: true
                default: '/dev'
        
jobs:
    manual-jobs:
        runs-on: ubuntu-latest
        steps:
        -   name: Exemple
            run: |
             echo "Hello world"
             echo "Env name: ${{ github.event.inputs.Environment }}"
           