name: Test Manual workflow

on:
    workflow_dispatch:
        
jobs:
    manual-jobs:
        runs-on: ubuntu-latest
        steps:
        -   name: Exemple
            run: echo "Hello World"
           