name: Test Manual workflow

on:
    workflow_dispatch:
        inputs:
            Environment:
                description: 'Environment to deploy'
                required: true
                default: '/dev'
        
jobs:
    manual-jobs:
        runs-on: ubuntu-latest
        environment: dev
        steps:
        -   name: Exemple
            run: |
             echo "Hello world"
             echo "Env name: ${{ github.event.inputs.Environment }}"

        -   name: github
            run: echo "${{ toJson(github)}}"

        -   name: runner
            run: echo "${{ toJson(runner)}}"

        -   name: secrets
            run: echo "${{ toJson(secrets)}}"

        -   name: secrets
            run: echo "${{ secrets.MY_API_URL }}"
           